"""Refresh hashes for the explicitly reviewed lightweight runtime pins."""

import json
from pathlib import Path
from urllib.request import urlopen


def main():
    directory = Path(__file__).resolve().parent
    lines = [
        "# Generated by lock_dependencies.py from requirements.in; review upgrades.",
        "# Install with --no-deps --require-hashes --only-binary=:all:.",
        "# All published wheel hashes allow Python 3.11/3.12 on supported platforms.",
    ]
    for requirement in (directory / "requirements.in").read_text().splitlines():
        if not requirement or requirement.startswith("#"):
            continue
        name, version = requirement.split("==")
        with urlopen(
            f"https://pypi.org/pypi/{name}/{version}/json", timeout=30
        ) as response:
            release = json.load(response)
        hashes = sorted(
            {
                file["digests"]["sha256"]
                for file in release["urls"]
                if file["packagetype"] == "bdist_wheel"
            }
        )
        if not hashes:
            raise RuntimeError(f"No wheels for {requirement}")
        lines.append(requirement + " \\")
        lines.extend(
            f"    --hash=sha256:{digest}" + (" \\" if index < len(hashes) - 1 else "")
            for index, digest in enumerate(hashes)
        )
    (directory / "requirements.lock").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
